<a href="https://colab.research.google.com/github/kerryback/2022-BUSI520/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy

Numpy is a wrapper to code written in C or a variant that performs fast mathematical operations.  Numpy functions operate element-wise on lists and return numpy arrays.

In [88]:
x = [1, 2, 3]
# np.sqrt(x)
# np.log(x)
# np.exp(x)

### Numpy arrays

* For lists, + concatenates and * duplicates.  For numpy arrays, + adds and * multiplies element-wise.
* Exponentiation in python is **.  It operates on numpy arrays element-wise.

In [89]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
# x + y
# x * y
# x**2
# 3**x

### Higher-dimensional arrays



In [90]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

The following illustrates a formatting convention that can make code more readable.  It is useful in many places and is not actually related to numpy arrays.  Arbitrary indentation is allowed inside parentheses or braces.

In [91]:
x = np.array(
    [ 
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Shape and reshape

In [92]:
x.shape

(3, 4)

In [93]:
x = np.array([i for i in range(1,13)]).reshape(3,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Some standard arrays

In [94]:
# np.ones(4)
# np.zeros(3)
# np.identity(3)

### Matrix algebra

In [95]:
x = np.array([i for i in range(1,13)]).reshape(3, 4)
y = np.array([1, 2, 5, 10])
x @ y

array([ 60, 132, 204])

In [96]:
x.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [97]:
x = norm.rvs(loc=0, scale=1, size=9).reshape(3, 3)
np.linalg.inv(x)

array([[-0.16727326,  1.16110398,  0.04869728],
       [ 4.89738219,  7.34113034,  1.72677252],
       [18.02517644, 28.42177388,  8.53461987]])

In [98]:
np.linalg.inv(x) @ x

array([[ 1.00000000e+00,  8.14852438e-18, -2.28861803e-17],
       [-5.00363020e-16,  1.00000000e+00, -1.14565095e-16],
       [-1.40396217e-15, -1.04401233e-15,  1.00000000e+00]])

### Concatenating numpy arrays

In [99]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6, 7])
np.concatenate((x, y))

array([1, 2, 3, 4, 5, 6, 7])

### Numpy array range

In [145]:
x = np.arange(5)
# 3 * x
# x ** 3
# 3 ** x
# x + x
# x * x